service: amazon
provider:
    name: aws
    runtime: nodejs6.10
    stage: dev
    region: us-east-1
    memorySize: 512
functions:
    test-tgdzrd: {handler: handler.test, events: [{http: {path: /test, method: post, private: false}}]}
